commands:
  help:
    permission: "dkenhanced.help"
  prott:
    permission: "dkenhanced.prott"
    prot_limit: 5
    greeting: "Sisenesite {PLAYER} alale."
    farewell: "Lahkusite {PLAYER} alalt."
    ride: true
  ev:
    timezone: "Europe/Tallinn"
db:
  mysql:
    host: ""
    port: 0
    database: ""
    username: ""
    password: ""
hindamine:

