name: DKEnhanced
version: 1.2.0
main: io.github.ukp123.dkenhanced.DKEnhanced
api-version: 1.14
authors: [ukp123]
description: Makes things go smoother for DKServer.
commands:
  dk:
    description: DKEnhanced põhikäsk.
    usage: /dk <arg>
  ttest:
    description: mdea
    usage: /ttest
  hinda:
    description: mdea
    usage: /hinda
permissions:
  dkenhanced.help:
    description: for /dk and /dk help
